<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ekawati Widyaningsih">
<meta name="dcterms.date" content="2023-01-19">

<title>UPAYA PEMERINTAH INDONESIA DALAM MENJAGA KETERSEDIAAN BAUKSIT DI MASA MENDATANG</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">UPAYA PEMERINTAH INDONESIA DALAM MENJAGA KETERSEDIAAN BAUKSIT DI MASA MENDATANG</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ekawati Widyaningsih </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang<img src="images/paste-A5C5DDD1.png" class="img-fluid"></h3>
<p>Perdagangan merupakan proses kegiatan yang berkaitan erat dengan pertukaran barang dan/atau jasa guna memperoleh imbalan atas barang/jasa yang ditawarkan. Ada berbagai jenis perdagangan di dunia ini, salah satunya adalah perdagangan internasional. Pengertian dari perdagangan internasional itu sendiri adalah hubungan perniagaan antara para pihak yang berada di dua negara yang berbeda, secara garis besar dilakukan dalam bentuk ekspor dan impor (Rinaldy Eddie,dkk. 2020).Kemudian jika dikutip dari Undang – Undang Nomor 7 Tahun 2014 Tentang Perdagangan, perdagangan internasional adalah Perdagangan yang mencakup kegiatan Ekspor dan/atau Impor atas Barang dan/atau Perdagangan Jasa yang melampaui batas wilayah negara. Jadi dapat disimpulkan bahwa perdagangan internasional adalah kegiatan mengeluarkan barang dari daerah pabean atau memasukkan barang ke daerah pabean.</p>
<p>Dalam kegiatan perdagangan internasional dapat kita temui berbagai kegiatan, umumnya disebut dengan kegiatan ekspor dan kegiatan impor. Menurut Undang – Undang Republik Indonesia Nomor 17 Tahun 2006 tentang Perubahan Atas Undang - Undang Nomor 10 Tahun 1995 tentang Kepabeanan, ekspor adalah kegiatan memasukkan barang ke dalam daerah pabean sedangkan impor adalah kegiatan mengeluarkan barang ke luar daerah pabean. Kedua proses perdagangan internasional tersebut dijalani oleh banyak pihak. Dalam kegiatan ekspor umumnya dilakukan oleh eksportir dan kegiatan impor dilakukan oleh importir. Menurut Undang – Undang Nomor 7 Tahun 2014 Tentang Perdagangan, eksportir adalah orang perseorangan atau lembaga atau badan usaha, baik yang berbentuk badan hukum maupun bukan badan hukum, yang melakukan Ekspor, sedangkan importir adalah orang perseorangan atau lembaga atau badan usaha baik yang berbentuk badan hukum maupun bukan badan hukum yang melakukan Impor.</p>
<p>Indonesia merupakan salah satu negara yang memiliki tingkat ekspor dan impor yang cukup tinggi pada beberapa komoditas. Indonesia ikut serta secara aktif dalam kegiatan ekspor dan impor, terlebih setelah tergabung pada World Trade Organization sejak tahun 1995 silam dan semakin meningkat sejak Indonesia ikut menyepakati perjanjian pedagangan bebas atau biasa dikenal dengan Free Trade Agreement (FTA). Dengan berbagai kesepakatan yang sudah disetujui dalam FTA, Indonesia memiliki akses tambahan dalam hal penghapusan tarif ekspor impor dan memperoleh akses hambatan non tarif dalam perdagangan barang, kemudian memperoleh keluasan akses pasar dan memperoleh kondisi pasar yang kondusif dalam menyediakan produk jasa dalam perdagangan jasa, dan memperoleh perlindungan dan dukungan investasi untuk pasar investasi.</p>
<p>Jika dilihat dari kondisi selama 3 tahun terakhir dimana terjadi kemunduran perkembangan dalam banyak aspek kehidupan dikarenakan terjadinya wabah penyakit baru yaitu wabah COVID – 19 membuat Indonesia juga menjadi salah satu negara yang terkena dampaknya. Menurut data dari <a href="http://www.trademap.org">www.trademap.org</a> 5 tahun terakhir, Indonesia mengalami penurunan nilai ekspor dan nilai impor yang cukup signifikan di tahun 2019 dan 2020 sekaligus mengalami perlambatan nilai ekspor dan nilai impor sejak tahun tersebut.</p>
<p><strong>DATA EKSPOR INDONESIA</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>JUMLAH EKSPOR INDONESIA ($)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>168.810.637,00</td>
</tr>
<tr class="even">
<td>2018</td>
<td>180.215.036,00</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>167.682.996,00</td>
</tr>
<tr class="even">
<td>2020</td>
<td>163.306.490,00</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>228.231.164,00</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-8D9B3C86.png" class="img-fluid"></p>
<p><strong>DATA IMPOR INDONESIA</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>JUMLAH IMPOR INDONESIA ($)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>158.925.150,00</td>
</tr>
<tr class="even">
<td>2018</td>
<td>188.711.246,00</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>1271.275.737,00</td>
</tr>
<tr class="even">
<td>2020</td>
<td>141.622.127,00</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>195.712.409,00</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-314324C1.png" class="img-fluid"></p>
<p>Jika dilihat dari data tersebut, tingkat ekspor dan impor Indonesia dalam 5 tahun terakhir terjadi penurunan di tahun 2018 s.d. 2020. Lalu keduanya berhasil meningkat kembali di tahun 2021. Kondisi ini terjadi karena pada tahun 2018 s.d. 2020 terjadi perubahan kondisi seluruh aspek kehidupan akibat wabah COVID - 19 dan Indonesia baru bisa kembali menyesuaikan diri terhitung sejak tahun 2021 sehingga menyebabkan angka ekspor dan impor baru bisa meningkat kembali pada tahun tersebut. Walaupun angka ekspor Indonesia terlihat cukup fluktuatif, akan tetapi terdapat beberapa komoditas yang memiliki jumlah ekspor yang semakin meningkat setiap tahunnya. Komoditas tersebut adalah komoditas dalam sektor barang tambang mineral.</p>
<p>Hasil tambang Indonesia cukup tinggi minatnya di pasar dunia. Hal itu dikarenakan Indonesia mampu menyediakan berbagai hasil tambang dalam jumlah yang besar. Hasil tambang tersebut sangat diperlukan bagi negara – negara besar dalam mengembangkan sektor industri hingga teknologi yang sedang mereka kembangkan. Terlihat sangat menguntungkan sebab Indonesia mampu memperoleh devisa negara yang cukup besar jika melakukan ekspor barang tambang mineral tersebut, terlebih ketersediaannya di Indonesia masih cukup tinggi. Akan tetapi akan jauh lebih menguntungkan jika Indonesia tidak melakukan ekspor komoditas hanya dalam bentuk mentahnya saja, tapi dalam bentuk komoditas yang sudah di olah. Hal itu dikarenakan harga jual komoditas mentah jauh lebih rendah dibandingkan harga jual komoditas olahan, namun Indonesia belum bisa melakukan pengolahan yang efektif untuk komoditas barang tambang mineral. Hasilnya Indonesia harus merelakan untuk mengekspor komoditas dalam bentuk mentah dengan jumlah yang banyak ke negara lain untuk di olah dan selanjutnya dimanfaatkan oleh negara tersebut. Keputusan yang dijalani Indonesia ini di nilai oleh Presiden Republik Indonesia Ke-7 yaitu Ir. Joko Widodo akan mengancam ketersediaan bahan baku mentah komoditas tambang mineral Indonesia di masa mendatang</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Bauksit adalah salah satu komoditas yang termasuk dalam golongan tambang mineral mentah. Jika dilihat dalam 5 tahun terakhir, saat ini komoditas bauksit sedang berada pada puncak daya minatnya. Hal itu terjadi karena menurut data dari <a href="http://www.katadata.id">www.katadata.id</a> , Indonesia merupakan salah satu negara penghasil bauksit terbesar ke – 6 di dunia, sehingga banyak negara yang mengimpor bauksit mentah dari Indonesia sebab Indonesia bisa menyediakan dalam jumlah yang banyak dan harga yang relatif lebih rendah jika dibandingkan dengan harga bauksit olahan. Selain dilihat dari segi harga dan jumlahnya, bauksit ini merupakan salah satu komoditas bernilai tinggi karena memiliki manfaat yang banyak. Bauksit bisa digunakan sebagai bahan produksi industri pipa, konstruksi, alat olahraga, penerbangan, kabel, alat rumah tangga, furnitur, hingga otomotif. Bauksit juga bisa dimanfaatkan sebagai pendukung dalam kosmetik, keramik, farmasi, dan pemurnian air.</p>
<p>Tingginya alternatif pemanfaatan komoditas bauksit, jika pengolahan bisa dilakukan secara maksimal maka dapat bermanfaat dalam meningkatkan devisa negara, membantu menstabilkan keadaan ekonomi suatu negara, membuka banyak lapangan kerja baru, dan mendorong pertumbuhan ekonomi ke arah yang lebih baik bagi Indonesia. Presiden Republik Indonesia Ke-7 yaitu Ir. Joko Widodo melihat potensi bauksit Indonesia jika di ekspor sebagai produk olahan atau produk jadi sehingga memutuskan untuk menerapkan beberapa kebijakan untuk meningkatkan efektivitas dalam meningkatkan daya jual bauksit sekaligus mengurangi ekspor berlebih terhadap bauksit mentah. Artikel ini akan membaha supaya yang dilakukan pemerintah Indonesia dalam menjaga ketersediaan bauksit di masa mendatang.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="1">
<li>Bagaimana efektivitas ekspor komoditas bauksit mentah terhadap pendapatan negara Indonesia?</li>
<li>Bagaimana kondisi ketersediaan bauksit mentah Indonesia di masa mendatang?</li>
<li>Bagaimana dampak yang ditimbulkan dengan semakin meningkatnya ekspor bauksit mentah Indonesia?</li>
<li>Bagaimana tanggapan pemerintah Indonesia terhadap dampak yang ditimbulkan dari semakin meningkatnya ekspor bauksit mentah?</li>
<li>Bagaimana upaya yang dilakukan oleh pemerintah Indonesia dalam mengatasi dampak yang ditimbulkan dari semakin meningkatnya ekspor bauksit mentah?</li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<ol type="1">
<li>Untuk mengetahui kontribusi yang diberikan dari kegiatan ekspor komoditas bauksit mentah terhadap pendapatan negara Indonesia</li>
<li>Untuk mengetahui prediksi ketersediaan bauksit mentah Indonesia di masa mendatang jika pada saat ini masih terus dijalani kegiatan ekspor bauksit mentah secara besar – besaran tanpa mementingkan resiko yang akan terjadi di masa mendatang</li>
<li>Untuk mengetahui dampak yang ditimbulkan karena melakukan ekspor bauksit mentah secara terus menerus tanpa mementingkan resiko yang akan hadir di masa mendatang</li>
<li>Untuk mengetahui tanggapan yang diberikan oleh pemerintah terhadap dampak yang ditimbulkan dari semakin meningkatnya ekspor bauksit mentah di Indonesia</li>
<li>Untuk mengetahui upaya yang dilakukan oleh pemerintah Indonesia dalam mengatasi dampak yang ditimbulkan dari semakin meningkatnya ekspor bauksit mentah</li>
</ol>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Package yang digunakan :</p>
<pre class="{library(tidyverse)}"><code>library(readxl)
library(tidyverse)</code></pre>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<ol type="1">
<li><p><strong>TEORI 1</strong></p>
<p>Hasil tambang mineral dan batu bara merupakan salah satu sumber daya alam yang berharga bagi Indonesia. Walaupun jumlahnya terhitung cukup banyak, akan tetapi melihat kondisinya yang sulit diperbaharui membuat Indonesia harus mengambil langkah untuk menghemat penggunaan bahan baku tersebut. Menyikapi hal tersebut, pemerintah Indonesia menetapkan Undang – Undang Nomor 4 Tahun 2009 Tentang Pertambangan Mineral Dan Batubara yang akan dijadikan dasar dalam pengelolaan komoditi pertambangan dan mineral.</p>
<p>Pada Undang – Undang tersebut menyebutkan tentang tujuan pengelolaan komoditi pertambangan mineral dan batu bara yaitu guna menjamin tersedianya mineral dan batu bara untuk kebutuhan dalam negeri dan membantu menyokong komoditi tersebut dalam bersaing pasar nasional, regional, dan internasional. Melihat tujuan tersebut, bisa disimpulkan bahwa komoditi mineral dan batu bara sepenuhnya dikuasai oleh negara dan akan dimanfaatkan demi meningkatkan kesejahteraan rakyat. Walaupun demikian, masing masing pemerintah daerah, pemerintah provinsi, dan pemerintah nasional memiliki wewenangnya sendiri dalam proses pemanfaatan komoditi mineral dan batu bara.</p>
<p>Beberapa wewenang dari masing – masing pemerintah yaitu berkenaan dengan penetapan wilayah pertambangan yang harus mempertimbangkan segala aspek kehidupan disekitar daerah tersebut, pemberian izin usaha pertambangan kepada suatu badan usaha, koperasi, atau perseorangan yang mampu memenuhi persyaratan administratif, persyaratan teknis, persyaratan lingkungan, dan persyaratan finansial. Kemudian pemerintah membatasi kepemilikan lahan hanya 1 hektare untuk perseorangan, 5 hektare untuk kelompok masyarakat, dan 10 hektare untuk koperasi. Semua izin kepemilikan tersebut hanya diberikan dalam jangka waktu 5 tahun maksimal dan dapat diperpanjang. Setelah kebijakan mengenai izin kepemilikan, pemerintah juga menetapkan batas maksimal jumlah produksi kegiatan pertambangan guna tetap menjaga ketersediaan untuk di masa mendatang</p></li>
<li><p><strong>TEORI 2</strong></p>
<p>Undang – Undang Nomor 3 Tahun 2020 tentang Pertambangan Mineral dan Batubara merupakan perubahan atas Undang Undang Nomor 4 Tahun 2009 tentang Pertambangan Mineral Batubara. Perubahan ini difokuskan pada pemberian kepastian terhadap investasi dalam jangka panjang, terutama bagi eksisting investor pemegang Izin Usaha Pertambangan, Perjanjian Karya Pengusahaan Pertambangan Batubara (PKP2B), Izin Usaha Pertambangan Khusus (IUPK), dan Kontrak Karya (KK). Kemudian juga terdapat perubahan penetapan sanksi yang diberikan kepada perusahaan yang tidak menjalankan proses reklamasi akan diberikan sanksi yang lebih berat. Lalu untuk menghindari proses pertambangan ilegal, pemerintah akan memberatkan hukuman bagi pihak yang melakukan aktivitas penambangan secara ilegal atau tanpa izin.</p>
<p>Perubahan yang dilakukan oleh pemerintah dinilai belum efektif, sebab masih ada pihak yang melihat kecacatan dari Undang – Undang tersebut. Perubahan ini dinilai menghapus hak kehidupan rakyat di lingkar tambang karena tidak memberikan jaminan keselamatan rakyat dan membuat peran negara semakin diperlemah sebab terdapat penghapusan pasal yang ammpu menutupi celah yang berpotensi menjadi praktek korupsi (Koordinator Jaringan Advokasi Tambang Kalimantan Timur, 2020). Selain dua poin utama tadi, terdapat juga penilaian bahwa Undang – Undang ini belum menjawab mengenai peningkatan nilai tambah mineral dan batu bara, terdapat beberapa tunggakan yang belum dibayarkan oleh perusahaan kepada negara, dan permasalahan pencemaran serta kerusakan lingkungan yang semakin hari semakin menghantui perkembangan kesehatan masyarakat.</p>
<p>Dengan adanya Undang-Undang tersebut Presiden Jokowi sempat beberapa kali melontarkan permintaan larangan ekspor bauksit pada saat Pertemuan Tahunan Bank Indonesia,&nbsp;24 November 2021. Jokowi mengatakan bahwa ini perlu dilakukan agar Indonesia tidak lagi menjual bahan mentah,melainkan harus bernilai tambah terlebih dahulu setelah melalui proses pengolahan dan pemurnian di dalam negeri.Dengan demikian,negara dan rakyat akan mendapatkan keuntungan lebih besar dibandingkan hanya menjual bahan mentah. Ini adalah bentuk upaya untuk menjaga ketersediaan. Oleh karenanya berdasarkan Undang-Undang tersebut,menjadi satu hal yang penting untuk menjaga ketersediaan bauksit di masa mendatang. Presiden Jokowi menerangkan berakhirnya periode penjualan atau periode ekspor mentah bauksit berencana akan berhenti ekspor pada 10 Juni 2023.</p></li>
<li><p><strong>KERANGKA PENELITIAN</strong></p>
<p><img src="images/paste-DAA14F70.png" class="img-fluid"></p>
<h2 id="metode-penelitian" data-number="3" class="anchored"><span class="header-section-number">3</span> Metode penelitian</h2></li>
</ol>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<ol type="1">
<li><p><strong>DATA PRODUKSI BAUKSIT INDONESIA TAHUN 2017 S.D. 2021 SEBAGAI VARIABEL X1</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>JUMLAH (DALAM RIBU TON)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>1.294</td>
</tr>
<tr class="even">
<td>2018</td>
<td>5.694</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>16.592</td>
</tr>
<tr class="even">
<td>2020</td>
<td>25.860</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>25.781</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-FAAA8799.png" class="img-fluid"></p></li>
<li><p><strong>DATA HARGA BAUKSIT INDONESIA TAHUN 2017 S.D. 2021 SEBAGAI VARIABEL X2</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>JUMLAH (DALAM $)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>2.114</td>
</tr>
<tr class="even">
<td>2018</td>
<td>2.099</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>1.809</td>
</tr>
<tr class="even">
<td>2020</td>
<td>1.675</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>2.397</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-F4FA646A.png" class="img-fluid"></p></li>
<li><p><strong>DATA JUMLAH PRODUKSI BAUKSIT INDONESIA TAHUN 2017 S.D. 2021 SEBAGAI VARIABEL Y</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>JUMLAH (DALAM RIBU TON)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>1.716,69</td>
</tr>
<tr class="even">
<td>2018</td>
<td>8.651,84</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>15.501,44</td>
</tr>
<tr class="even">
<td>2020</td>
<td>19.378,03</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>19.914,48</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-66A70157.png" class="img-fluid"></p></li>
<li><p><strong>IMPLEMENTASI DATA X1 DAN DATA X2 TERHADAP DATA Y</strong></p></li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th>TAHUN</th>
<th>PRODUKSI (X1)</th>
<th>HARGA (X2)</th>
<th>EKSPOR (Y)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017</td>
<td>1.294</td>
<td>2.114</td>
<td>1.716,69</td>
</tr>
<tr class="even">
<td>2018</td>
<td>5.694</td>
<td>2.099</td>
<td>8.651,84</td>
</tr>
<tr class="odd">
<td>2019</td>
<td>16.592</td>
<td>1.809</td>
<td>15.501,44</td>
</tr>
<tr class="even">
<td>2020</td>
<td>25.860</td>
<td>1.675</td>
<td>19.378,03</td>
</tr>
<tr class="odd">
<td>2021</td>
<td>25.781</td>
<td>2.397</td>
<td>19.914,48</td>
</tr>
</tbody>
</table>
<p><img src="images/paste-5FC69EEA.png" class="img-fluid"></p>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
✔ ggplot2 3.3.6      ✔ purrr   0.3.5 
✔ tibble  3.1.8      ✔ dplyr   1.0.10
✔ tidyr   1.2.1      ✔ stringr 1.4.1 
✔ readr   2.1.3      ✔ forcats 0.5.2 
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X1,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"JUMLAH PRODUKSI BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X2,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>dat)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = dat)

Residuals:
      1       2       3       4       5 
-2006.7  1877.6  1232.5 -1226.2   122.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 5083.4120  8615.0349   0.590   0.6149  
X1             0.6684     0.1022   6.537   0.0226 *
X2            -1.0525     4.1330  -0.255   0.8228  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2301 on 2 degrees of freedom
Multiple R-squared:  0.9561,    Adjusted R-squared:  0.9121 
F-statistic: 21.75 on 2 and 2 DF,  p-value: 0.04395</code></pre>
</div>
</div>
<p>Analisis menggunakan metode regresi multivariat atau dengan regresi linear sederhana yang menggunakan data numerik yang diproses pada R studio sebagai alat bantu dengan package readxl dan tidyverse. Analisis dilakukan dengan menggunakan 3 data yaitu data jumlah ekspor bauksit Indonesia yang berperan sebagai variabel Y, lalu data jumlah produksi bauksit Indonesia yang berperan sebagai variabel X1, dan data harga bauksit Indonesia yang berperan sebagai variabel X2. Ketiga data tersebut merupakan data yang didapatkan pada tahun 2017 s.d. 2021 dimana variabel X1 dan X2 menjadi variabel independen dan variabel Y sebagai variabel dependen. Tujuan dari analisis adalah untuk mengetahui plot dan regresi antara variabel terkait, sehingga bisa mengetahui hubungan antara jumlah produksi bauksit Indonesia dan harga bauksit Indonesia terhadap jumlah ekspor bauksit Indonesia</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<ol type="1">
<li><p>Plot Variabel independen X1 dan Variabel dependen Y</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X1,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"JUMLAH PRODUKSI BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ini merupakan hasil plot dari variabel independen X1 yang merupakan data jumlah produksi bauksit Indonesia dengan variabel dependen Y yang merupakan data jumlah ekspor bauksit Indonesia. Hasil plot ini didapatkan dengan melakukan run pada command :</p></li>
<li><p>Plot Variabel independen X2 dan Variabel dependen Y</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X2,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Ini merupakan hasil plot dari variabel independen X2 yang merupakan data harga bauksit Indonesia dengan variabel dependen Y yang merupakan data jumlah ekspor bauksit Indonesia. Hasil plot ini didapatkan dengan melakukan run pada command :</p></li>
<li><p>Regresi Varibel Y dengan Variabel X1 + Variabel X2</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X1,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"JUMLAH PRODUKSI BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X2,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>dat)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = dat)

Residuals:
      1       2       3       4       5 
-2006.7  1877.6  1232.5 -1226.2   122.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 5083.4120  8615.0349   0.590   0.6149  
X1             0.6684     0.1022   6.537   0.0226 *
X2            -1.0525     4.1330  -0.255   0.8228  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2301 on 2 degrees of freedom
Multiple R-squared:  0.9561,    Adjusted R-squared:  0.9121 
F-statistic: 21.75 on 2 and 2 DF,  p-value: 0.04395</code></pre>
</div>
</div>
<p>Ini merupakan hasil regresi variabel independen X1 dan variabel independen X2 terhadap variabel dependen Y. Hasil regresi ini didapatkan dengan melakukan run pada command :</p>
<ol start="4" type="1">
<li><p>GGPLOT HUBUNGAN JUMLAH PRODUKSI BAUKSIT (X1)TERHADAP JUMLAH EKSPOR BAUKSIT INDONESIA(Y)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X1,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"JUMLAH PRODUKSI BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X2,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>dat)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = dat)

Residuals:
      1       2       3       4       5 
-2006.7  1877.6  1232.5 -1226.2   122.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 5083.4120  8615.0349   0.590   0.6149  
X1             0.6684     0.1022   6.537   0.0226 *
X2            -1.0525     4.1330  -0.255   0.8228  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2301 on 2 degrees of freedom
Multiple R-squared:  0.9561,    Adjusted R-squared:  0.9121 
F-statistic: 21.75 on 2 and 2 DF,  p-value: 0.04395</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>X1,<span class="at">y=</span>Y)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"HUBUNGAN JUMLAH PRODUKSI BAUKSIT INDONESIA TERHADAP JUMLAH EKSPOR BAUKSIT INDONESIA"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x1=</span><span class="st">"PRODUKSI BAUKSIT INDONESIA"</span>,</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"JUMLAH EKSPOR BAUKSI INDONESIA"</span>,</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: BPS, TRADE MAP, DATABOKS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid" width="672"></p>
</div>
</div></li>
<li><p>GGPLOT HUBUNGAN HARGA BAUKSIT (X2) TERHADAP JUMLAH EKSPOR BAUKSIT INDONESIA (Y)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"D:/DATA EKSPOR BAUKSIT INDONESIA"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'readxl'</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">'tidyverse'</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'Produksi Bauksit Indonesia.xlsx'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>New names:
• `` -&gt; `...1`</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X1,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"JUMLAH PRODUKSI BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dat<span class="sc">$</span>X2,dat<span class="sc">$</span>Y,<span class="at">xlab=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,<span class="at">ylab=</span><span class="st">"JUMLAH EKSPOR BAUKSIT INDONESIA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(Y<span class="sc">~</span>X1<span class="sc">+</span>X2,<span class="at">data=</span>dat)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X1 + X2, data = dat)

Residuals:
      1       2       3       4       5 
-2006.7  1877.6  1232.5 -1226.2   122.8 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) 5083.4120  8615.0349   0.590   0.6149  
X1             0.6684     0.1022   6.537   0.0226 *
X2            -1.0525     4.1330  -0.255   0.8228  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2301 on 2 degrees of freedom
Multiple R-squared:  0.9561,    Adjusted R-squared:  0.9121 
F-statistic: 21.75 on 2 and 2 DF,  p-value: 0.04395</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>X2,<span class="at">y=</span>Y)) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"HUBUNGAN HARGA BAUKSIT TERHADAP JUMLAH EKSPOR BAUKSIT INDONESIA"</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>       <span class="at">x2=</span><span class="st">"HARGA BAUKSIT INDONESIA"</span>,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"JUMLAH EKSPOR BAUKSI INDONESIA"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: BPS, TRADE MAP, DATABOKS"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid" width="672"></p>
</div>
</div></li>
</ol></li>
</ol>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Dari hasil regresi yang didapatkan, kita dapat memperoleh model persamaan =</p>
<p>Y = 5083,4120 + 0,6684X1 - 1,0525X2</p>
<ol type="1">
<li><p>Konstanta (intercept)</p>
<p>Nilai intercept bernilai positif sebesar 5083,4120 yang menggambarkan jumlah ekspor bauksit Indonesia ke dunia meningkat sejumlah 5083,4120 ribu ton dengan anggapan jumlah produksi bauksit Indonesia dan harga jual bauksit Indonesia adalah 0</p></li>
<li><p>Persamaan regresi menunjukkan bahwa jumlah produksi bauksit Indonesia memiliki koefisien regresi 0,6684 dan signifikan sehingga memiliki arti apabila produksi bauksit Indonesia meningkat sebesar 1000 ton maka jumlah ekspor bauksit Indonesia ke dunia akan naik sebesar 0,6684 ribu ton. Hasil tersebut menjelaskan bahwa jumlah produksi bauksit Indonesia memiliki pengaruh positif dan signifikan terhadap jumlah ekspor bauksit Indonesia ke dunia. Hal ini berarti jika Indonesia mampu meningkatkan jumlah produksi bauksit mentahnya maka akan membantu meningkatkan jumlah ekspor bauksit Indonesia ke seluruh dunia</p></li>
<li><p>Harga bauksit Indonesia memiliki koefisien regresi -1,0525 yang memiliki arti jika harga bauksit Indonesia naik sebesar 1 USD maka jumlah ekspor bauksit Indonesia akan turun 1,0525 ribu ton/tahun. Hasil tersebut menjelaskan bahwa harga bauksit Indonesia memiliki pengaruh negarif bagi jumlah ekspor bauksit Indonesia ke seluruh dunia. Hal itu dikarenakan apabila harga bauksit mentah Indonesia mengalami peningkatan maka akan terjadi penurunan minat beli konsumen terhadap komoditas tersebut. Jadi akan sesuai dengan teori permintaan dan penawaran yang menyebutkan bahwa apabila terjadi kenaikan harga maka akan menyebabkan penurunan jumlah permintaan konsumen.</p></li>
</ol>
<p>Jadi melihat dari regresi yang dihasilkan, bisa menjadi gambaran bagi pemerintah dalam menentukan upaya yang dilakukan. Pemerintah harus mampu memastikan agar kenaikan harga yang terjadi kedepannya tidak mengurangi tingkat minat konsumen sebab pemerintah berencana untuk meningkatkan mutu komoditas yang tadinya bahan mentah menjadi bahan olahan. Oleh karena itu, upaya yang harus diambil adalah memastikan daya beli konsumen tetap tinggi pada saat harga komoditas meningkat diikuti tapi harus diikuti oleh perbaikan dari kualitas komoditas tersebut.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Berdasarkan pengujian terhadap variabel penelitian, bisa ditarik kesimpulan sebagai berikut :</p>
<ol type="1">
<li>Jumlah produksi bauksit Indonesia berpengaruh positif dan signifikan terhadap jumlah ekspor bauksit Indonesia ke seluruh dunia dengan nilai 0,6684. Itu artinya apabila jumlah produksi sebesar meningkat 1000 ton maka jumlah ekspor bauksit Indonesia ke seluruh dunia akan naik sebesar 0,6684 ribu ton.</li>
<li>Harga bauksit Indonesia berpengaruh negatif dan tidak signifikan terhadap jumlah ekspor bauksit Indonesia ke seluruh dunia dengan nilai koefisien -1,0525 yang memiliki arti jika harga bauksit Indonesia naik sebesar 1 USD maka jumlah ekspor bauksit Indonesia akan turun 1,0525 ribu ton/tahun. Hal itu dikarenakan apabila harga bauksit mentah Indonesia mengalami peningkatan maka akan terjadi penurunan minat beli konsumen terhadap komoditas tersebut.</li>
<li>Dari 2 variabel independen hanya ada 1 variabel yang berpengaruh positif dan signifikan dan 1 variabel lainnya berpengaruh negatif tetapi tidak signifikan. Oleh karena itu, jumlah produksi jauh lebih berpengaruh terhadap kegiatan ekspornya. Jadi pemerintah bisa melakukan upaya untuk meningkatkan jumlah produksi, akan tetapi harus tetap berupaya melakukan pengolahan untuk meningkatkan nilai komoditas tersebut sehingga bisa di jual dengan harga yang lebih tinggi tetapi dengan diikuti kualitas yang lebih baik juga. Upaya itu dilakukan juga guna menekan angka ekspor komoditas bauksit mentah, sebab kalau terlalu sering melakukan ekspor bahan mentah akan mengancam ketersediaannya dimasa mendatang.</li>
<li>Variabel independen 2 (X2) berpengaruh negatif karena pada saat ini Indonesia hanya mampu mengekspor dalam bentuk mentahnya saja, jadi kenaikan harga yang terjadi dinilai merugikan konsumen karena mereka masih harus mengeluarkan biaya untuk mengolah komoditas</li>
</ol>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Ahdiat, A. (2022). <em>Nilai Ekspor Bauksit Indonesia (2017-2021)</em>. <a href="https://databoks.katadata.co.id/datapublish/2022/09/29/ekspor-bauksit-ri-melesat-hampir-10-kali-lipat-dalam-lima-tahun" class="uri">https://databoks.katadata.co.id/datapublish/2022/09/29/ekspor-bauksit-ri-melesat-hampir-10-kali-lipat-dalam-lima-tahun</a></p>
<p>Badan Pusat Statistik. (2021). <em>Produksi Barang Tambang Mineral 2019-2021</em>. <a href="https://www.bps.go.id/indicator/10/508/1/produksi-barang-tambang-mineral.html" class="uri">https://www.bps.go.id/indicator/10/508/1/produksi-barang-tambang-mineral.html</a></p>
<p>Badan Pusat Statistik. (2021). <em>Produksi Barang Tambang Mineral 2015-2018</em>. <a href="https://www.bps.go.id/indicator/10/508/2/produksi-barang-tambang-mineral.html" class="uri">https://www.bps.go.id/indicator/10/508/2/produksi-barang-tambang-mineral.html</a></p>
<p>CNN INDONESIA, T. (2022). <em>Alasan Indonesia Setop Ekspor Bauksit</em>. <a href="https://www.cnnindonesia.com/ekonomi/20221221201445-85-890483/alasan-indonesia-setop-ekspor-bauksit" class="uri">https://www.cnnindonesia.com/ekonomi/20221221201445-85-890483/alasan-indonesia-setop-ekspor-bauksit</a></p>
<p>CNN INDONESIA, T. (2022). <em>INFOGRAFIS: Larangan Ekspor Bijih Bauksit Indonesia</em>. <a href="https://www.cnnindonesia.com/ekonomi/20221222144325-88-890810/infografis-larangan-ekspor-bijih-bauksit-indonesia" class="uri">https://www.cnnindonesia.com/ekonomi/20221222144325-88-890810/infografis-larangan-ekspor-bijih-bauksit-indonesia</a></p>
<p>Fauzi, A. (2017). MOTIVASI INDONESIA MENGHENTIKAN EKSPOR MINERAL MENTAH JENIS BAUKSIT KE TIONGKOK PASCA PEMBERLAKUAN UNDANG UNDANG MINERBA NO.4 TAHUN 2009. <em>JOM FISIP</em>, <em>4</em>. <a href="https://jom.unri.ac.id/index.php/JOMFSIP/article/view/13846/13407" class="uri">https://jom.unri.ac.id/index.php/JOMFSIP/article/view/13846/13407</a></p>
<p>Haknuh, M. M. (2022). <em>Jokowi Ekspor Bauksit, Cek Prospek Emitennya!</em> <a href="https://www.cnbcindonesia.com/market/20221223161924-17-399667/jokowi-ekspor-bauksit-cek-prospek-emitennya?page=all" class="uri">https://www.cnbcindonesia.com/market/20221223161924-17-399667/jokowi-ekspor-bauksit-cek-prospek-emitennya?page=all</a></p>
<p>Kementerian Energi dan Sumber Daya Mineral. (2021). <em>Harga Acuan Bauksit 2017 s.d. 2021</em>. <a href="https://www.minerba.esdm.go.id/harga_acuan" class="uri">https://www.minerba.esdm.go.id/harga_acuan</a></p>
<p>Kementerian Komunikasi dan Informatika Republik Indonesia. (2022). <em>Pemerintah akan Berlakukan Larangan Ekspor Bijih Bauksit Mulai Juni 2023</em>. <a href="https://www.kominfo.go.id/content/detail/46457/pemerintah-akan-berlakukan-larangan-ekspor-bijih-bauksit-mulai-juni-2023/0/berita" class="uri">https://www.kominfo.go.id/content/detail/46457/pemerintah-akan-berlakukan-larangan-ekspor-bijih-bauksit-mulai-juni-2023/0/berita</a></p>
<p>Khadafi, Y. Y. (2020). <em>UU Minerba Dinilai Bermasalah dan Tak Menjawab Permasalahan</em>. <a href="https://betahita.id/news/detail/5381/uu-minerba-dinilai-bermasalah-dan-tak-menjawab-permasalahan.html?v=1594019060" class="uri">https://betahita.id/news/detail/5381/uu-minerba-dinilai-bermasalah-dan-tak-menjawab-permasalahan.html?v=1594019060</a></p>
<p>Laily, I. N. (2022). <em>Perdagangan Internasional: Pengertian, Tujuan, Manfaat, dan Hambatan</em>. <a href="https://katadata.co.id/iftitah/berita/625e22f7caae6/perdagangan-internasional-pengertian-tujuan-manfaat-dan-hambatan" class="uri">https://katadata.co.id/iftitah/berita/625e22f7caae6/perdagangan-internasional-pengertian-tujuan-manfaat-dan-hambatan</a></p>
<p>Pahlevi, R. (2022). <em>ESDM Setop Ekspor Bauksit pada 2023, Ini Produksinya di RI</em>. <a href="https://databoks.katadata.co.id/datapublish/2022/06/22/esdm-setop-ekspor-bauksit-pada-2023-ini-produksinya-di-ri" class="uri">https://databoks.katadata.co.id/datapublish/2022/06/22/esdm-setop-ekspor-bauksit-pada-2023-ini-produksinya-di-ri</a></p>
<p>Pemerintah Pusat. (2006). <em>UNDANG-UNDANG REPUBLIK INDONESIA NOMOR 17 TAHUN 2006 TENTANG PERUBAHAN ATAS UNDANG-UNDANG NOMOR 10 TAHUN 1995 TENTANG KEPABEANAN</em>. <a href="https://repository.beacukai.go.id/peraturan/2006/12/uu_17-2006.pdf" class="uri">https://repository.beacukai.go.id/peraturan/2006/12/uu_17-2006.pdf</a></p>
<p>Pemerintah Pusat. (2009). <em>UNDANG-UNDANG REPUBLIK INDONESIA NOMOR 4 TAHUN 2009 TENTANG PERTAMBANGAN MINERAL DAN BATUBARA</em>. <a href="https://peraturan.bpk.go.id/Home/Details/38578/uu-no-4-tahun-2009" class="uri">https://peraturan.bpk.go.id/Home/Details/38578/uu-no-4-tahun-2009</a></p>
<p>Pemerintah Pusat. (2014). <em>UNDANG-UNDANG REPUBLIK INDONESIA NOMOR 7 TAHUN 2014 TENTANG PERDAGANGAN</em>. <a href="https://peraturan.bpk.go.id/Home/Details/38584/uu-no-7-tahun-2014" class="uri">https://peraturan.bpk.go.id/Home/Details/38584/uu-no-7-tahun-2014</a></p>
<p>Pemerintah Pusat. (2020). <em>UNDANG-UNDANG REPUBLIK INDONESIA NOMOR 3 TAHUN 2O2O TENTANG PERUBAHAN ATAS UNDANG-UNDANG NOMOR 4 TAHUN 2OO9 TENTANG PERTAMBANGAN MINERAL DAN BATUBARA</em>. <a href="https://peraturan.bpk.go.id/Home/Details/138909/uu-no-3-tahun-2020#:~:text=UU%20No.%203%20Tahun%202020,dan%20Batubara%20%5BJDIH%20BPK%20RI%5D" class="uri">https://peraturan.bpk.go.id/Home/Details/138909/uu-no-3-tahun-2020#:~:text=UU%20No.%203%20Tahun%202020,dan%20Batubara%20%5BJDIH%20BPK%20RI%5D</a></p>
<p>Pratama, S. I. (2023). <em>Jokowi Larang Ekspor Bijih Bauksit Mulai Juni 2023</em>. <a href="https://betahita.id/news/detail/8282/jokowi-larang-ekspor-bijih-bauksit-mulai-juni-2023.html?v=1671897567" class="uri">https://betahita.id/news/detail/8282/jokowi-larang-ekspor-bijih-bauksit-mulai-juni-2023.html?v=1671897567</a></p>
<p>Rusidi. (2021). <em>Regrasi Linier Sederhana (Simple Linear Regression)</em>. <a href="https://bookdown.org/moh_rosidi2610/Metode_Numerik/datamod.html#reglin" class="uri">https://bookdown.org/moh_rosidi2610/Metode_Numerik/datamod.html#reglin</a></p>
<p>Setiawan, V. N. (2023). <em>Menteri ESDM Ungkap Alasan Jokowi Setop Ekspor Bauksit</em>. <a href="https://www.cnbcindonesia.com/news/20230103115926-4-402373/menteri-esdm-ungkap-alasan-jokowi-setop-ekspor-bauksit" class="uri">https://www.cnbcindonesia.com/news/20230103115926-4-402373/menteri-esdm-ungkap-alasan-jokowi-setop-ekspor-bauksit</a></p>
<p>Trade Map. (2021). <em>List of importing markets for a product exported by IndonesiaMetadata Product: TOTAL All products</em>. <a href="https://www.trademap.org/Country_SelProductCountry_TS.aspx?nvpm=1%7c360%7c%7c%7c%7cTOTAL%7c%7c%7c2%7c1%7c1%7c2%7c2%7c1%7c2%7c1%7c1%7c1">https://www.trademap.org/Country_SelProductCountry_TS.aspx nvpm=1%7c360%7c%7c%7c%7cTOTAL%7c%7c%7c2%7c1%7c1%7c2%7c2%7c1%7c2%7c1%7c1%7c1</a></p>
<p>Trade Map. (2021). <em>List of supplying markets for a product imported by IndonesiaMetadata Product: TOTAL All products</em>. <a href="https://www.trademap.org/Country_SelProductCountry_TS.aspx?nvpm=1%7c360%7c%7c%7c%7cTOTAL%7c%7c%7c2%7c1%7c1%7c1%7c2%7c1%7c2%7c1%7c1%7c1" class="uri">https://www.trademap.org/Country_SelProductCountry_TS.aspx?nvpm=1%7c360%7c%7c%7c%7cTOTAL%7c%7c%7c2%7c1%7c1%7c1%7c2%7c1%7c2%7c1%7c1%7c1</a></p>
<p>Widhiyanto, F. (2022). <em>Hilirisasi Bauksit Tingkatkan Pendapatan Negara Rp 62 T</em>. <a href="https://www.beritasatu.com/ekonomi/1011545/hilirisasi-bauksit-tingkatkan-pendapatan-negara-rp-62-t" class="uri">https://www.beritasatu.com/ekonomi/1011545/hilirisasi-bauksit-tingkatkan-pendapatan-negara-rp-62-t</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>